version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "eJOCNb9AYvLy6DDurdswtpX3Vp1s2HWM5FmXhmD6KCTmd+Nd9vs5MhCVVeP5l4Lp3lI8Ly7FQyHNIFcOFljPVD263M1vHW0dk2JqjLgZGiZS3vtk+NymPQhQVhLs62IBFmg+vNqYpQgQ/rZhdXTbeLV9mAI4uQzAjNL2oM7fi2XTcjmceDjG1W7bZoFo6tXsuw/GjcQMZalgzTJ4s1FU63AaU2C1Arnh7wWZJAjTXaYUG2E9uAzZBiqOL6CNGWzQylLdfAbIlgX2D3MBcv3DC7RgBYEW21daS31COdRigWq7RwdZnsy0JNctblgTHzBrTltxG6aDxUod6mEIi/s/PmFmb3XNaw113TK1G+r57Dt/evkXX2UQzrJyGa5L3/J06caHg+2YSXeL3hs+/AxOKPE5+nzYfT/pmAfztcf8e4WzAlD3WoWab5x75xz+FID2JSFTsgeGiSgTg2ezyLaxgmHGSSde8LHt7nYs3EwC0NumsVnv0MjcFzbWpdrYtR20JdybwqbOQ3Camym0yBEXSOjLz9DjfaAFuAYRk7KKLNRvkRNx1+4K0ejhE5/vf0cgcBgx/1ss4dwYo2cCwBF8EoqMp5R/pdxqWgxNERB3sXO93r6QCXwyZFaWVocdfv9WSZ8YTS0+2kpNo4fY6AQ0hVSZDJJnTm5jTE5Z8PHyYS4="
    - secure: "dzRbk9pKN4hJXvclIKYI9JFmv5nQUfS4mJsMkJsoGXpxKq9R2zqYfDY9HFlX/y1L667sHWP1HhXvrEb6w0x4nqC2A3Oe3rTFLCJOA/hAGg9SsICQDTxdipt3evZvbUJAgeoxjn2WpbfY1bYwi2N4VrVoUxUSGp/CIarbFffDCSpG24hNxVk83dPRhMYzVwB3K0xkENEgmzbvEzXOwp/J7NSS2bT6wI4zNuFErAKqAaDb3SbwTuknK3HLSGus0FDvTB0mkej34sy4cZwYpXXzkyo9Ob/ulSwV4XNzv3BVcqY9gnVf3z3GtofiBUkni5eJZjSaUpTt/S0kIiIpdIlKxqnBCUQ1H8+t2wq0OTdpR0QalOpzv/bhP32ss6xegO4oK4vws5IJv4PbJ3JK+JKLE/apH5UCIjpHxOcSicjnt93I3pttMBt/v94vWsSSRRlb77MH+kvo0TUjIJ5IfdqSxOh3aPX2+NY5auotp8o5NI06qNUUXk+6GJdCiVKoTYnzKjLw1z34A9XCVgcjYWwqq+mTrfWGBXf1wlGoPr3rnh5dKYUpo/cAHIrsBsieZInAUz2GrUXlw/JN6P6m/IFA0eyq08MJHb1JMGca2cXcWL2p+E2eiyeBcMwG+kPpVk3QXY0dIdPIzuJifpMvpwyR2s/y64UTTuLJlxWKSq/7eCc="
